// ─────────────────────────────────────────────────────────────────────────────

// Boot sequence:
//   1. WidgetsFlutterBinding.ensureInitialized()
//   2. System UI chrome (immersive dark)
//   3. Firebase.initializeApp()
//   4. Supabase.initialize()
//   5. ServiceLocator.init()   ← registers all singletons (get_it)
//   6. runApp(EkklisiaApp())
//
// Background FCM is registered as a top-level function in notification_service.
// ─────────────────────────────────────────────────────────────────────────────
import 'dart:async';

import 'package:audio_service/audio_service.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

import 'app.dart';
import 'core/constants/app_constants.dart';
import 'core/di/service_locator.dart';
import 'features/agbeya/cubit/audio_player_cubit.dart';
import 'firebase_options.dart'; // generated by flutterfire configure
import 'services/audio_service.dart';
import 'services/notification_service.dart'
    show firebaseMessagingBackgroundHandler;

// ── Background FCM handler (must be top-level) ────────────────────────────────
// Re-exported from notification_service.dart so it is visible to Firebase.
// The @pragma annotation is already applied there; we just ensure it's
// registered before runApp via Firebase.initializeApp.

// ── Audio service bootstrap ───────────────────────────────────────────────────
// Extracted so the try-catch doesn't swallow unrelated boot errors.
Future<void> _initAudioService() async {
  try {
    final audioHandler = await AudioService.init<AgbeyaAudioHandler>(
      builder: AgbeyaAudioHandler.new,
      config: const AudioServiceConfig(
        androidNotificationChannelId: 'com.ekklisia.audio',
        androidNotificationChannelName: 'Ekklisia',
        androidNotificationOngoing: true,
        androidStopForegroundOnPause: true,
        notificationColor: Color(0xFF1B2A4A),
      ),
    );
    sl.registerSingleton<AgbeyaAudioHandler>(audioHandler);
    sl.registerSingleton<AudioPlayerCubit>(AudioPlayerCubit(audioHandler));
    debugPrint('[Audio] AudioService initialized (background playback active)');
  } catch (e) {
    // Plugin not yet compiled — happens the first run after adding audio_service
    // to pubspec.yaml without a full cold rebuild.
    // The app still launches; run `flutter pub get && flutter run` to fix.
    debugPrint('[Audio] AudioService init failed — falling back to direct mode: $e');
    final handler = AgbeyaAudioHandler();
    sl.registerSingleton<AgbeyaAudioHandler>(handler);
    sl.registerSingleton<AudioPlayerCubit>(AudioPlayerCubit(handler));
  }
}

Future<void> main() async {
  // Catch asynchronous errors outside of Flutter framework
  await runZonedGuarded(
        () async {
      // ── 1. Flutter binding ─────────────────────────────────────────────────
      WidgetsFlutterBinding.ensureInitialized();

      // ── 2. Set preferred orientation ──────────────────────────────────────
      await SystemChrome.setPreferredOrientations([
        DeviceOrientation.portraitUp,
        DeviceOrientation.portraitDown,
      ]);

      // ── System UI will be updated dynamically based on theme in app.dart ────
      // This default will be overridden by the app's theme mode

      // ── 3. Global Flutter error handler ───────────────────────────────────
      FlutterError.onError = (FlutterErrorDetails details) {
        FlutterError.presentError(details);
        // TODO: forward to Crashlytics in production
        // FirebaseCrashlytics.instance.recordFlutterFatalError(details);
      };

      // ── 4. Firebase ──────────────────────────────────────────────────────
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );

      // ── 5. Supabase ──────────────────────────────────────────────────────
      await Supabase.initialize(
        url:     AppConstants.supabaseUrl,
        anonKey: AppConstants.supabaseAnonKey,
        debug:   false, // set to true during development
      );

      // ── 6. Dependency injection ─────────────────────────────────────────
      await ServiceLocator.init();

      // ── 7. Background audio service ──────────────────────────────────────
      // AudioService.init() links the Dart handler to the platform's media
      // controls (Android foreground service, iOS AVAudioSession).
      //
      // IMPORTANT — after adding audio_service to pubspec.yaml you MUST do a
      // full cold build before this works:
      //
      //   flutter pub get
      //   flutter run          ← full restart, NOT hot-reload / hot-restart
      //
      // The try-catch below means the app still launches during development
      // even if the native plugin isn't compiled yet; background playback
      // (lock screen controls) won't work until the full rebuild is done.
      await _initAudioService();

      // ── 8. Launch ────────────────────────────────────────────────────────
      runApp(const EkklisiaApp());
    },
        (error, stack) {
      debugPrint('[Ekklisia] Uncaught error: $error');
      debugPrintStack(stackTrace: stack);
      // TODO: FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
    },
  );
}