// ─────────────────────────────────────────────────────────────────────────────

// Boot sequence:
//   1. WidgetsFlutterBinding.ensureInitialized()
//   2. System UI chrome (immersive dark)
//   3. Firebase.initializeApp()
//   4. Supabase.initialize()
//   5. ServiceLocator.init()   ← registers all singletons (get_it)
//   6. runApp(EkkleiciaApp())
//
// Background FCM is registered as a top-level function in notification_service.
// ─────────────────────────────────────────────────────────────────────────────
import 'dart:async';

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

import 'app.dart';
import 'core/constants/app_constants.dart';
import 'core/di/service_locator.dart';
import 'firebase_options.dart'; // generated by flutterfire configure
import 'services/notification_service.dart'
    show firebaseMessagingBackgroundHandler;

// ── Background FCM handler (must be top-level) ────────────────────────────────
// Re-exported from notification_service.dart so it is visible to Firebase.
// The @pragma annotation is already applied there; we just ensure it's
// registered before runApp via Firebase.initializeApp.

Future<void> main() async {
  // Catch asynchronous errors outside of Flutter framework
  await runZonedGuarded(
        () async {
      // ── 1. Flutter binding ─────────────────────────────────────────────────
      WidgetsFlutterBinding.ensureInitialized();

      // ── 2. Immersive dark system chrome ───────────────────────────────────
      await SystemChrome.setPreferredOrientations([
        DeviceOrientation.portraitUp,
        DeviceOrientation.portraitDown,
      ]);
      SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
        statusBarColor:                 Color(0xFF08111C), // bgDeep
        statusBarIconBrightness:        Brightness.light,
        systemNavigationBarColor:       Color(0xFF08111C),
        systemNavigationBarIconBrightness: Brightness.light,
      ));

      // ── 3. Global Flutter error handler ───────────────────────────────────
      FlutterError.onError = (FlutterErrorDetails details) {
        FlutterError.presentError(details);
        // TODO: forward to Crashlytics in production
        // FirebaseCrashlytics.instance.recordFlutterFatalError(details);
      };

      // ── 4. Firebase ──────────────────────────────────────────────────────
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );

      // ── 5. Supabase ──────────────────────────────────────────────────────
      await Supabase.initialize(
        url:     AppConstants.supabaseUrl,
        anonKey: AppConstants.supabaseAnonKey,
        debug:   false, // set to true during development
      );

      // ── 6. Dependency injection ─────────────────────────────────────────
      await ServiceLocator.init();

      // ── 7. Launch ───────────────────────────────────────────────────────
      runApp(const EkkleiciaApp());
    },
        (error, stack) {
      debugPrint('[Ekklicia] Uncaught error: $error');
      debugPrintStack(stackTrace: stack);
      // TODO: FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
    },
  );
}